Models/Master.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AspNetMVCRouting_Prakhar.DAL;

namespace AspNetMVCRouting_Prakhar.Models
{
   
    public class Master
    {
        public int MasterId { get; set; }
        public string MasterName { get; set; }
        
    }
    public class MasterData
    {
        DataAccess db = new DataAccess();
        public SelectList LoadMaster(int procid)
        {
            return new SelectList(db.Proc_BindMaster(procid).ToList(), "MasterId", "MasterName");
        }
        public SelectList LoadMasterById(int procid, int id)
        {
            return new SelectList(db.Proc_BindMasterById(procid, id).ToList(), "MasterId", "MasterName");
        }
    }
}

Models/Students.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AspNetMVCRouting_Prakhar.Models
{
    public class Students
    {
        public int StudentId { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public string MobileNo { get; set; }
        public string msg { get; set; }
        public int CityId { get; set; }
        public int StateId { get; set; }
        public string City { get; set; }
        public int CityId1 { get; set; }
        public string State { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AspNetMVCRouting_Prakhar.Models;
using AspNetMVCRouting_Prakhar.DAL;


namespace AspNetMVCRouting_Prakhar.Controllers
{
    public class HomeController : Controller
    {
        DataAccess DB = new DataAccess();
        private int procid;
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About(string id)
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
       // [Route("DoubleRoute")]
        public ActionResult Contact(string id , string pid)
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult AddStudent()
        {
            Students Model = new Students();
            if (Request.QueryString["sid"] != null)
            {
                Model.StudentId = Convert.ToInt32(Request.QueryString["sid"].ToString());
                Model = DB.AddStudentswithCity(3, Model).ToList().FirstOrDefault();
                ViewBag.buttonName = "Update";
            }
            else
            {
                ViewBag.buttonName = "Submit";
            }

            var list1 = DB.AddStudentswithCity(4, Model).ToList();
            if (list1.Count > 0)
                ViewBag.list = list1;
            else
                ViewBag.list = null;

            return View(Model);
        }
        [HttpPost]
        public ActionResult AddStudent(Students Model, string command)
        {
            if (command == "Submit")
                procid = 1;
            else if (command == "Update")
                procid = 2;
            var list = DB.AddStudentswithCity(procid, Model).ToList();
            if (list.Count > 0)
            {
                if(list[0].msg == "success")
                {
                    TempData["msg"] = "1";
                }
                else if(list[0].msg == "exists")
                {
                    TempData["msg"] = "2";
                }
                else if (list[0].msg == "update")
                {
                    TempData["msg"] = "3";
                }
                else
                {
                    TempData["msg"] = "4";
                }
                ViewBag.list = list;
            }
            else
            {
                ViewBag.list = null;
            }
            return RedirectToAction("AddStudent", "Home");
        }
        public ActionResult EditStudent(int id)
        {
            Students Model = new Students();
            return RedirectToAction("AddStudent", new { sid = id });
        }

        public JsonResult StudentDelete(int sid)
        {
            Students Model = new Students();
            Model.StudentId = sid;
            var data = DB.AddStudentswithCity(5, Model).ToList().FirstOrDefault();
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AspNetMVCRouting_Prakhar.DAL;

namespace AspNetMVCRouting_Prakhar.Controllers
{
    public class MasterController : Controller
    {
        // GET: Master
        DataAccess DB = new DataAccess();
      
        #region Single Value Master
        public JsonResult getToMasterSingle(int Procid)
        {
            return Json(DB.Proc_BindMaster(Procid), JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Two Value Master
        public JsonResult getToMaster(int Procid, int id)
        {
            var data = DB.Proc_BindMasterById(Procid, id);
            return Json(data, JsonRequestBehavior.AllowGet);
            //return Json(DB.Proc_BindMasterById(Procid, id), JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/AddStudent.cshtml
@model AspNetMVCRouting_Prakhar.Models.Students
    @using AspNetMVCRouting_Prakhar.Models
@{
    ViewBag.Title = "AddStudent";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var message = TempData["msg"] ?? string.Empty;
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script type="text/javascript">
      var message = '@message';
    if (message == "1")
        alert("Record Save Successfully!");
    else if (message == "2")
        alert("Record already Exists !");
        else if (message == "3")
        alert("Record Update Successfully!");



    function StudentDelete(sid) {
        var result = confirm("Delete Selected Record No.?");
        if (result) {
           $.ajax({
                url: "@Url.Action("StudentDelete", "Home")",
                type: 'post',
                datatype: 'json',
                data: { sid: sid },
                asycs: false,
                success: function (isConfirm) {
                alert("Your Record Deleted Successfully!");
                location.reload();
                 }
             });
        }
    }

    function loadCity() {
        $("#CityId").empty();
        var id = $("#StateId").val();

        $.ajax({
            url: "@Url.Action("getToMaster", "Master")",
            datatype: "json",
            type: "post",
            data: { Procid: 1, id: id },
            async: false,
            success: function (data) {
                $.each(data, function (i, d) {
                    $("select[id='CityId']").append($('<option></option>').val(d.MasterId).html(d.MasterName));
                });
            }
        });
    }
    $(document).ready(function () {
       
        var CityId1 = $("#CityId1").val();
        var CityId = $("#CityId").val();
        
        if (CityId1 == null || CityId1 == 0) {
            loadCity();
        }
        else {
            if (CityId != null) {
                loadCity();
                $('select[id="CityId"] option[value=' + $("#CityId1").val() + ']').attr("selected", "selected");
            }

        }
    })
</script>

<main class="app-content">
    <div class="app-title">
        <div>
            <h1><i class="fa fa-edit"></i>Student</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item">Student</li>
            <li class="breadcrumb-item"><a href="#">Student</a></li>
        </ul>
    </div>
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(m => m.StudentId, new { @id = "StudentId" })
        @Html.HiddenFor(m => m.CityId1, new { @id = "CityId1" })
        <div class="row">
            <div class="col-md-12">
                <div class="tile">
                    <section class="invoice">
                        <div class="row invoice-info">
                            <div class="col-4">
                                <div class="form-group">
                                    <span style="color: red;">*</span>&nbsp;<label for="lblName">Student Name</label>
                                       @Html.TextBoxFor(m => m.Name, new { @id = "Name", @class = "form-control", @required = "required" })
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <span style="color: red;">*</span>&nbsp;<label for="lblName">Class</label>
                                    @Html.TextBoxFor(m => m.Class, new { @id = "Class", @class = "form-control", @required = "required" })
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <span style="color: red;">*</span>&nbsp;<label for="lblName">Mobile No</label>
                                    @Html.TextBoxFor(m => m.MobileNo, new { @id = "MobileNo", @class = "form-control", @required = "required" })
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <span style="color: red;">*</span>&nbsp;<label for="lblName">State</label>
                                    @Html.DropDownListFor(m => m.StateId, (new MasterData()).LoadMaster(1), new { @id = "StateId", @class = "form-control", @onchange = "loadCity()" })
                                </div>
                            </div> 
                            <div class="col-4">
                                <div class="form-group">
                                    <span style="color: red;">*</span>&nbsp;<label for="lblName">City </label>
                                    @Html.DropDownListFor(m => m.CityId, new SelectListItem[] { new SelectListItem { Text = "--Select--", Value = "0" } }, new { @id = "CityId", @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="tile-footer">
                            @*<button class="btn btn-primary" type="submit"  name="Command" value="@ViewBag.buttonName"><i class="fa fa-fw fa-lg fa-check-circle"></i></button>*@
                            <input type="submit" id="btnSUbmit" class="btn btn-primary" name="Command" value="@ViewBag.buttonName" />
                            &nbsp;&nbsp;&nbsp;
                            <input type="reset" class="btn btn-secondary" value="Reset" />
                            @*<a class="btn btn-secondary" href="#"><i class="fa fa-fw fa-lg fa-times-circle"></i>Cancel</a>*@
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-12">
                                <div class="tile">
                                    <div class="tile-body">
                                        <table class="table table-hover table-bordered" id="sampleTable">
                                            <thead>
                                                <tr>
                                                    <th>
                                                        S.No.
                                                    </th>

                                                    <th>
                                                        Name
                                                    </th>
                                                    <th>
                                                        Mobile No
                                                    </th><th>
                                                        Class
                                                    </th><th>
                                                        City
                                                    </th><th>
                                                        State
                                                    </th>
                                                    <th>
                                                        Action
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @{ var sn = 1; }
                                                @if (ViewBag.list != null)
                                                {
                                                    foreach (var item in ViewBag.list)
                                                    {
                                                        <tr>
                                                            <td>
                                                                @(sn++)
                                                            </td>

                                                            <td>
                                                                @item.Name
                                                            </td>
                                                            <td>
                                                                @item.MobileNo
                                                            </td> <td>
                                                                @item.Class
                                                            </td> <td>
                                                                @item.City
                                                            </td> <td>
                                                                @item.State
                                                            </td>
                                                            <td style="text-align:center">
                                                                <a title='Edit' onclick="location.href='@Url.Action("EditStudent", "Home", new { id = @item.StudentId })'">
                                                                    <i class="fa fa-edit btn-sm btn-info">Edit</i>
                                                                </a>
                                                                <a title='Delete' onclick='StudentDelete( @item.StudentId)' href="#">
                                                                    <i class="fa fa-times btn-sm btn-danger">Delete</i>
                                                                </a>
                                                            </td>

                                                        </tr>
                                                    }
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    }
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <a class="btn btn-danger" href="@Url.Action("About","Home",new { @id= "prakhar-srivastava"})">Click Me</a>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <a class="btn btn-warning" href="@Url.Action("Contact","Home",new { @id= "prakhar-srivastava",@pid="Happy-Coding"})">Click Me</a>


    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>